#include "sol_render.h"

#include <cstddef>
#include <cstdio>
#include <cstring>

namespace sol {

    // Generated by glslc -mfmt=c at build time; see engine/CMakeLists.txt.
    static const u32 kStaticMeshVertSpv[] =
#include "static_mesh.vert.inl"
        ;
    static const u32 kStaticMeshFragSpv[] =
#include "static_mesh.frag.inl"
        ;

    static const VkClearValue kClearColor = { { { 0.05f, 0.05f, 0.07f, 1.0f } } };

#if defined( _DEBUG )
    constexpr bool kEnableValidation = true;
#else
    constexpr bool kEnableValidation = false;
#endif

    static const char * kValidationLayer = "VK_LAYER_KHRONOS_validation";
    static const char * kDeviceExtensions[] = { VK_KHR_SWAPCHAIN_EXTENSION_NAME };

#define VK_CHECK( expr )                                                            \
    do {                                                                            \
        VkResult vkCheckResult = ( expr );                                          \
        if( vkCheckResult != VK_SUCCESS ) {                                         \
            fprintf( stderr, "Vulkan call failed (%d) at %s:%d\n",                  \
                     (int)vkCheckResult, __FILE__, __LINE__ );                      \
            return false;                                                           \
        }                                                                           \
    } while( 0 )

    static VKAPI_ATTR VkBool32 VKAPI_CALL DebugCallback(
        VkDebugUtilsMessageSeverityFlagBitsEXT severity,
        VkDebugUtilsMessageTypeFlagsEXT type,
        const VkDebugUtilsMessengerCallbackDataEXT * data,
        void * userData ) {
        SPLATS_UNUSED( type );
        SPLATS_UNUSED( userData );
        if( severity >= VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT ) {
            fprintf( stderr, "[vulkan] %s\n", data->pMessage );
        }
        return VK_FALSE;
    }

    static bool HasValidationLayer() {
        u32 count = 0;
        vkEnumerateInstanceLayerProperties( &count, nullptr );
        if( count == 0 ) {
            return false;
        }

        VkLayerProperties layers[64] = {};
        if( count > SPLATS_ARRAY_COUNT( layers ) ) {
            count = (u32)SPLATS_ARRAY_COUNT( layers );
        }
        vkEnumerateInstanceLayerProperties( &count, layers );

        for( u32 i = 0; i < count; i++ ) {
            if( strcmp( layers[i].layerName, kValidationLayer ) == 0 ) {
                return true;
            }
        }
        return false;
    }

    static void FillDebugMessengerInfo( VkDebugUtilsMessengerCreateInfoEXT * info ) {
        *info = {};
        info->sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT;
        info->messageSeverity = VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT |
                                VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT;
        info->messageType = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT |
                            VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT |
                            VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT;
        info->pfnUserCallback = DebugCallback;
    }

    static bool CreateInstance( Renderer * r, const char * const * requiredExtensions,
                                u32 requiredCount, bool useValidation ) {
        VkApplicationInfo appInfo = {};
        appInfo.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
        appInfo.pApplicationName = "Solum";
        appInfo.applicationVersion = VK_MAKE_VERSION( 0, 1, 0 );
        appInfo.pEngineName = "Solum";
        appInfo.engineVersion = VK_MAKE_VERSION( 0, 1, 0 );
        appInfo.apiVersion = VK_API_VERSION_1_3;

        const char * extensions[16] = {};
        u32 extCount = 0;
        for( u32 i = 0; i < requiredCount && extCount < SPLATS_ARRAY_COUNT( extensions ) - 1; i++ ) {
            extensions[extCount++] = requiredExtensions[i];
        }
        if( useValidation ) {
            extensions[extCount++] = VK_EXT_DEBUG_UTILS_EXTENSION_NAME;
        }

        VkDebugUtilsMessengerCreateInfoEXT debugInfo = {};
        FillDebugMessengerInfo( &debugInfo );

        VkInstanceCreateInfo createInfo = {};
        createInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
        createInfo.pApplicationInfo = &appInfo;
        createInfo.enabledExtensionCount = extCount;
        createInfo.ppEnabledExtensionNames = extensions;
        if( useValidation ) {
            createInfo.enabledLayerCount = 1;
            createInfo.ppEnabledLayerNames = &kValidationLayer;
            // Chained so the layer also reports problems with instance creation itself.
            createInfo.pNext = &debugInfo;
        }

        VK_CHECK( vkCreateInstance( &createInfo, nullptr, &r->instance ) );

        if( useValidation ) {
            auto create = (PFN_vkCreateDebugUtilsMessengerEXT)vkGetInstanceProcAddr(
                r->instance, "vkCreateDebugUtilsMessengerEXT" );
            if( create != nullptr ) {
                create( r->instance, &debugInfo, nullptr, &r->debugMessenger );
            }
        }
        return true;
    }

    static bool DeviceSupportsSwapchain( VkPhysicalDevice device ) {
        u32 count = 0;
        vkEnumerateDeviceExtensionProperties( device, nullptr, &count, nullptr );
        if( count == 0 ) {
            return false;
        }

        static VkExtensionProperties props[512] = {};
        if( count > SPLATS_ARRAY_COUNT( props ) ) {
            count = (u32)SPLATS_ARRAY_COUNT( props );
        }
        vkEnumerateDeviceExtensionProperties( device, nullptr, &count, props );

        for( u32 i = 0; i < count; i++ ) {
            if( strcmp( props[i].extensionName, VK_KHR_SWAPCHAIN_EXTENSION_NAME ) == 0 ) {
                return true;
            }
        }
        return false;
    }

    static bool FindQueueFamilies( VkPhysicalDevice device, VkSurfaceKHR surface,
                                   u32 * graphics, u32 * present ) {
        u32 count = 0;
        vkGetPhysicalDeviceQueueFamilyProperties( device, &count, nullptr );

        VkQueueFamilyProperties families[32] = {};
        if( count > SPLATS_ARRAY_COUNT( families ) ) {
            count = (u32)SPLATS_ARRAY_COUNT( families );
        }
        vkGetPhysicalDeviceQueueFamilyProperties( device, &count, families );

        bool foundGraphics = false;
        bool foundPresent = false;
        for( u32 i = 0; i < count; i++ ) {
            if( !foundGraphics && ( families[i].queueFlags & VK_QUEUE_GRAPHICS_BIT ) ) {
                *graphics = i;
                foundGraphics = true;
            }

            VkBool32 canPresent = VK_FALSE;
            vkGetPhysicalDeviceSurfaceSupportKHR( device, i, surface, &canPresent );
            if( !foundPresent && canPresent == VK_TRUE ) {
                *present = i;
                foundPresent = true;
            }
        }
        return foundGraphics && foundPresent;
    }

    static bool PickPhysicalDevice( Renderer * r ) {
        u32 count = 0;
        vkEnumeratePhysicalDevices( r->instance, &count, nullptr );
        if( count == 0 ) {
            fprintf( stderr, "No Vulkan-capable GPU found\n" );
            return false;
        }

        VkPhysicalDevice devices[16] = {};
        if( count > SPLATS_ARRAY_COUNT( devices ) ) {
            count = (u32)SPLATS_ARRAY_COUNT( devices );
        }
        vkEnumeratePhysicalDevices( r->instance, &count, devices );

        // Prefer a discrete GPU, but take any device that can draw and present.
        VkPhysicalDevice fallback = VK_NULL_HANDLE;
        u32 fallbackGraphics = 0;
        u32 fallbackPresent = 0;

        for( u32 i = 0; i < count; i++ ) {
            u32 graphics = 0;
            u32 present = 0;
            if( !DeviceSupportsSwapchain( devices[i] ) ) {
                continue;
            }
            if( !FindQueueFamilies( devices[i], r->surface, &graphics, &present ) ) {
                continue;
            }

            VkPhysicalDeviceProperties props = {};
            vkGetPhysicalDeviceProperties( devices[i], &props );
            if( props.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU ) {
                r->physicalDevice = devices[i];
                r->graphicsFamily = graphics;
                r->presentFamily = present;
                printf( "GPU: %s\n", props.deviceName );
                return true;
            }
            if( fallback == VK_NULL_HANDLE ) {
                fallback = devices[i];
                fallbackGraphics = graphics;
                fallbackPresent = present;
            }
        }

        if( fallback == VK_NULL_HANDLE ) {
            fprintf( stderr, "No GPU with graphics + present + swapchain support\n" );
            return false;
        }

        r->physicalDevice = fallback;
        r->graphicsFamily = fallbackGraphics;
        r->presentFamily = fallbackPresent;

        VkPhysicalDeviceProperties props = {};
        vkGetPhysicalDeviceProperties( fallback, &props );
        printf( "GPU: %s\n", props.deviceName );
        return true;
    }

    static bool CreateLogicalDevice( Renderer * r ) {
        f32 priority = 1.0f;
        VkDeviceQueueCreateInfo queueInfos[2] = {};
        u32 queueCount = 0;

        queueInfos[queueCount].sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
        queueInfos[queueCount].queueFamilyIndex = r->graphicsFamily;
        queueInfos[queueCount].queueCount = 1;
        queueInfos[queueCount].pQueuePriorities = &priority;
        queueCount++;

        if( r->presentFamily != r->graphicsFamily ) {
            queueInfos[queueCount].sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
            queueInfos[queueCount].queueFamilyIndex = r->presentFamily;
            queueInfos[queueCount].queueCount = 1;
            queueInfos[queueCount].pQueuePriorities = &priority;
            queueCount++;
        }

        // Vertex handles are point sprites, and a point wider than one pixel
        // needs largePoints. Asked for only where the device has it, since
        // requesting a feature it does not support fails device creation.
        VkPhysicalDeviceFeatures supported = {};
        vkGetPhysicalDeviceFeatures( r->physicalDevice, &supported );

        VkPhysicalDeviceFeatures features = {};
        features.largePoints = supported.largePoints;
        r->largePoints = supported.largePoints == VK_TRUE;

        VkDeviceCreateInfo createInfo = {};
        createInfo.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
        createInfo.queueCreateInfoCount = queueCount;
        createInfo.pQueueCreateInfos = queueInfos;
        createInfo.pEnabledFeatures = &features;
        createInfo.enabledExtensionCount = (u32)SPLATS_ARRAY_COUNT( kDeviceExtensions );
        createInfo.ppEnabledExtensionNames = kDeviceExtensions;
        // No enabledLayerCount here: device layers are deprecated, and passing
        // any is a spec violation. The instance layer covers the device too.

        VK_CHECK( vkCreateDevice( r->physicalDevice, &createInfo, nullptr, &r->device ) );

        vkGetDeviceQueue( r->device, r->graphicsFamily, 0, &r->graphicsQueue );
        vkGetDeviceQueue( r->device, r->presentFamily, 0, &r->presentQueue );
        return true;
    }

    // Every buffer and image the renderer owns is suballocated out of this.
    // Built against the statically linked loader, matching VMA_STATIC_VULKAN_
    // FUNCTIONS in vendor/vma_impl.cpp.
    static bool CreateAllocator( Renderer * r ) {
        VmaAllocatorCreateInfo createInfo = {};
        createInfo.physicalDevice = r->physicalDevice;
        createInfo.device = r->device;
        createInfo.instance = r->instance;
        // Has to match the apiVersion the instance was created with, or VMA
        // will call entry points the driver never promised.
        createInfo.vulkanApiVersion = VK_API_VERSION_1_3;
        VK_CHECK( vmaCreateAllocator( &createInfo, &r->allocator ) );
        return true;
    }

    static VkSurfaceFormatKHR ChooseSurfaceFormat( VkPhysicalDevice device, VkSurfaceKHR surface ) {
        u32 count = 0;
        vkGetPhysicalDeviceSurfaceFormatsKHR( device, surface, &count, nullptr );

        VkSurfaceFormatKHR formats[64] = {};
        if( count > SPLATS_ARRAY_COUNT( formats ) ) {
            count = (u32)SPLATS_ARRAY_COUNT( formats );
        }
        vkGetPhysicalDeviceSurfaceFormatsKHR( device, surface, &count, formats );

        for( u32 i = 0; i < count; i++ ) {
            if( formats[i].format == VK_FORMAT_B8G8R8A8_UNORM &&
                formats[i].colorSpace == VK_COLOR_SPACE_SRGB_NONLINEAR_KHR ) {
                return formats[i];
            }
        }
        return formats[0];
    }

    static VkExtent2D ChooseExtent( const VkSurfaceCapabilitiesKHR & caps, const Renderer * r ) {
        // 0xFFFFFFFF means "the surface takes whatever the swapchain asks for".
        if( caps.currentExtent.width != 0xFFFFFFFFu ) {
            return caps.currentExtent;
        }

        VkExtent2D extent = { (u32)r->fallbackWidth, (u32)r->fallbackHeight };
        if( extent.width < caps.minImageExtent.width )   { extent.width = caps.minImageExtent.width; }
        if( extent.width > caps.maxImageExtent.width )   { extent.width = caps.maxImageExtent.width; }
        if( extent.height < caps.minImageExtent.height ) { extent.height = caps.minImageExtent.height; }
        if( extent.height > caps.maxImageExtent.height ) { extent.height = caps.maxImageExtent.height; }
        return extent;
    }

    static bool CreateSwapchain( Renderer * r ) {
        VkSurfaceCapabilitiesKHR caps = {};
        VK_CHECK( vkGetPhysicalDeviceSurfaceCapabilitiesKHR( r->physicalDevice, r->surface, &caps ) );

        VkSurfaceFormatKHR format = ChooseSurfaceFormat( r->physicalDevice, r->surface );
        VkExtent2D extent = ChooseExtent( caps, r );

        u32 imageCount = caps.minImageCount + 1;
        if( caps.maxImageCount > 0 && imageCount > caps.maxImageCount ) {
            imageCount = caps.maxImageCount;
        }
        if( imageCount > (u32)kMaxSwapchainImages ) {
            imageCount = (u32)kMaxSwapchainImages;
        }

        VkSwapchainCreateInfoKHR createInfo = {};
        createInfo.sType = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR;
        createInfo.surface = r->surface;
        createInfo.minImageCount = imageCount;
        createInfo.imageFormat = format.format;
        createInfo.imageColorSpace = format.colorSpace;
        createInfo.imageExtent = extent;
        createInfo.imageArrayLayers = 1;
        createInfo.imageUsage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
        createInfo.preTransform = caps.currentTransform;
        createInfo.compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
        // FIFO is the only mode required to exist, and it is vsync.
        createInfo.presentMode = VK_PRESENT_MODE_FIFO_KHR;
        createInfo.clipped = VK_TRUE;
        createInfo.oldSwapchain = VK_NULL_HANDLE;

        u32 families[2] = { r->graphicsFamily, r->presentFamily };
        if( r->graphicsFamily != r->presentFamily ) {
            createInfo.imageSharingMode = VK_SHARING_MODE_CONCURRENT;
            createInfo.queueFamilyIndexCount = 2;
            createInfo.pQueueFamilyIndices = families;
        } else {
            createInfo.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
        }

        VK_CHECK( vkCreateSwapchainKHR( r->device, &createInfo, nullptr, &r->swapchain ) );

        u32 actualCount = 0;
        vkGetSwapchainImagesKHR( r->device, r->swapchain, &actualCount, nullptr );
        if( actualCount > (u32)kMaxSwapchainImages ) {
            fprintf( stderr, "Swapchain returned %u images, only %d supported\n",
                     actualCount, kMaxSwapchainImages );
            return false;
        }
        vkGetSwapchainImagesKHR( r->device, r->swapchain, &actualCount, r->swapchainImages );

        r->swapchainImageCount = (i32)actualCount;
        r->swapchainFormat = format.format;
        r->swapchainExtent = extent;

        for( i32 i = 0; i < r->swapchainImageCount; i++ ) {
            VkImageViewCreateInfo viewInfo = {};
            viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
            viewInfo.image = r->swapchainImages[i];
            viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
            viewInfo.format = r->swapchainFormat;
            viewInfo.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
            viewInfo.subresourceRange.levelCount = 1;
            viewInfo.subresourceRange.layerCount = 1;
            VK_CHECK( vkCreateImageView( r->device, &viewInfo, nullptr, &r->swapchainImageViews[i] ) );

            r->imagesInFlight[i] = VK_NULL_HANDLE;
        }
        return true;
    }

    static bool FormatHasStencil( VkFormat format ) {
        return format == VK_FORMAT_D32_SFLOAT_S8_UINT || format == VK_FORMAT_D24_UNORM_S8_UINT;
    }

    static bool ChooseDepthFormat( Renderer * r ) {
        // D32 first: no stencil to carry around, and it is universally supported
        // on desktop. The packed formats are the fallback.
        const VkFormat candidates[] = {
            VK_FORMAT_D32_SFLOAT,
            VK_FORMAT_D32_SFLOAT_S8_UINT,
            VK_FORMAT_D24_UNORM_S8_UINT,
        };

        for( u64 i = 0; i < SPLATS_ARRAY_COUNT( candidates ); i++ ) {
            VkFormatProperties props = {};
            vkGetPhysicalDeviceFormatProperties( r->physicalDevice, candidates[i], &props );
            if( props.optimalTilingFeatures & VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT ) {
                r->depthFormat = candidates[i];
                return true;
            }
        }

        fprintf( stderr, "No usable depth attachment format\n" );
        return false;
    }

    static void DestroyDepthResources( Renderer * r ) {
        if( r->depthView != VK_NULL_HANDLE ) {
            vkDestroyImageView( r->device, r->depthView, nullptr );
            r->depthView = VK_NULL_HANDLE;
        }
        if( r->depthImage != VK_NULL_HANDLE ) {
            vmaDestroyImage( r->allocator, r->depthImage, r->depthAllocation );
            r->depthImage = VK_NULL_HANDLE;
            r->depthAllocation = VK_NULL_HANDLE;
        }
    }

    static bool CreateDepthResources( Renderer * r ) {
        if( !ChooseDepthFormat( r ) ) {
            return false;
        }

        VkImageCreateInfo imageInfo = {};
        imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
        imageInfo.imageType = VK_IMAGE_TYPE_2D;
        imageInfo.format = r->depthFormat;
        imageInfo.extent.width = r->swapchainExtent.width;
        imageInfo.extent.height = r->swapchainExtent.height;
        imageInfo.extent.depth = 1;
        imageInfo.mipLevels = 1;
        imageInfo.arrayLayers = 1;
        imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
        imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
        imageInfo.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
        imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        // The render pass transitions it out of UNDEFINED on first use.
        imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;

        // A full-screen attachment is exactly the case VMA recommends a
        // dedicated block for: it is large, and it dies with the swapchain
        // rather than alongside the meshes it shares a pool with.
        VmaAllocationCreateInfo allocInfo = {};
        allocInfo.usage = VMA_MEMORY_USAGE_AUTO;
        allocInfo.flags = VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT;
        allocInfo.requiredFlags = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
        VK_CHECK( vmaCreateImage( r->allocator, &imageInfo, &allocInfo, &r->depthImage,
                                  &r->depthAllocation, nullptr ) );

        VkImageViewCreateInfo viewInfo = {};
        viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
        viewInfo.image = r->depthImage;
        viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
        viewInfo.format = r->depthFormat;
        // A packed depth/stencil view has to name both aspects to be attachable.
        viewInfo.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
        if( FormatHasStencil( r->depthFormat ) ) {
            viewInfo.subresourceRange.aspectMask |= VK_IMAGE_ASPECT_STENCIL_BIT;
        }
        viewInfo.subresourceRange.levelCount = 1;
        viewInfo.subresourceRange.layerCount = 1;
        VK_CHECK( vkCreateImageView( r->device, &viewInfo, nullptr, &r->depthView ) );
        return true;
    }

    static bool CreateRenderPass( Renderer * r ) {
        VkAttachmentDescription color = {};
        color.format = r->swapchainFormat;
        color.samples = VK_SAMPLE_COUNT_1_BIT;
        color.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
        color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
        color.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
        color.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
        color.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        color.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

        // Cleared every frame and never read afterwards, so there is nothing to
        // store when the pass ends.
        VkAttachmentDescription depth = {};
        depth.format = r->depthFormat;
        depth.samples = VK_SAMPLE_COUNT_1_BIT;
        depth.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
        depth.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
        depth.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
        depth.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
        depth.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        depth.finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

        VkAttachmentReference colorRef = {};
        colorRef.attachment = 0;
        colorRef.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

        VkAttachmentReference depthRef = {};
        depthRef.attachment = 1;
        depthRef.layout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

        VkSubpassDescription subpass = {};
        subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
        subpass.colorAttachmentCount = 1;
        subpass.pColorAttachments = &colorRef;
        subpass.pDepthStencilAttachment = &depthRef;

        // Holds off the layout transition until the image has actually been
        // acquired. The fragment-test stages are in here too, because the depth
        // clear is a write that must not race the previous frame's reads.
        VkSubpassDependency dependency = {};
        dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
        dependency.dstSubpass = 0;
        dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                  VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT |
                                  VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
        dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                                  VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT |
                                  VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
        dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
                                   VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;

        // Order here is the attachment index the refs above point at.
        const VkAttachmentDescription attachments[] = { color, depth };

        VkRenderPassCreateInfo createInfo = {};
        createInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
        createInfo.attachmentCount = (u32)SPLATS_ARRAY_COUNT( attachments );
        createInfo.pAttachments = attachments;
        createInfo.subpassCount = 1;
        createInfo.pSubpasses = &subpass;
        createInfo.dependencyCount = 1;
        createInfo.pDependencies = &dependency;

        VK_CHECK( vkCreateRenderPass( r->device, &createInfo, nullptr, &r->renderPass ) );
        return true;
    }

    static bool CreateFramebuffers( Renderer * r ) {
        for( i32 i = 0; i < r->swapchainImageCount; i++ ) {
            // Every framebuffer shares the one depth view; only one frame is in
            // the render pass at a time.
            const VkImageView attachments[] = { r->swapchainImageViews[i], r->depthView };

            VkFramebufferCreateInfo createInfo = {};
            createInfo.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
            createInfo.renderPass = r->renderPass;
            createInfo.attachmentCount = (u32)SPLATS_ARRAY_COUNT( attachments );
            createInfo.pAttachments = attachments;
            createInfo.width = r->swapchainExtent.width;
            createInfo.height = r->swapchainExtent.height;
            createInfo.layers = 1;
            VK_CHECK( vkCreateFramebuffer( r->device, &createInfo, nullptr, &r->framebuffers[i] ) );
        }
        return true;
    }

    static bool CreatePerImageSemaphores( Renderer * r ) {
        VkSemaphoreCreateInfo semaphoreInfo = {};
        semaphoreInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;

        for( i32 i = 0; i < r->swapchainImageCount; i++ ) {
            VK_CHECK( vkCreateSemaphore( r->device, &semaphoreInfo, nullptr, &r->renderFinished[i] ) );
        }
        return true;
    }

    static bool CreateCommandsAndSync( Renderer * r ) {
        VkCommandPoolCreateInfo poolInfo = {};
        poolInfo.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
        poolInfo.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
        poolInfo.queueFamilyIndex = r->graphicsFamily;
        VK_CHECK( vkCreateCommandPool( r->device, &poolInfo, nullptr, &r->commandPool ) );

        VkCommandBufferAllocateInfo allocInfo = {};
        allocInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        allocInfo.commandPool = r->commandPool;
        allocInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        allocInfo.commandBufferCount = (u32)kFramesInFlight;
        VK_CHECK( vkAllocateCommandBuffers( r->device, &allocInfo, r->commandBuffers ) );

        VkSemaphoreCreateInfo semaphoreInfo = {};
        semaphoreInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;

        VkFenceCreateInfo fenceInfo = {};
        fenceInfo.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
        // Created signalled, so the very first frame does not wait forever.
        fenceInfo.flags = VK_FENCE_CREATE_SIGNALED_BIT;

        for( i32 i = 0; i < kFramesInFlight; i++ ) {
            VK_CHECK( vkCreateSemaphore( r->device, &semaphoreInfo, nullptr, &r->imageAvailable[i] ) );
            VK_CHECK( vkCreateFence( r->device, &fenceInfo, nullptr, &r->frameInFlight[i] ) );
        }
        return true;
    }

    static void DestroySwapchain( Renderer * r ) {
        for( i32 i = 0; i < r->swapchainImageCount; i++ ) {
            if( r->framebuffers[i] != VK_NULL_HANDLE ) {
                vkDestroyFramebuffer( r->device, r->framebuffers[i], nullptr );
                r->framebuffers[i] = VK_NULL_HANDLE;
            }
            if( r->renderFinished[i] != VK_NULL_HANDLE ) {
                vkDestroySemaphore( r->device, r->renderFinished[i], nullptr );
                r->renderFinished[i] = VK_NULL_HANDLE;
            }
            if( r->swapchainImageViews[i] != VK_NULL_HANDLE ) {
                vkDestroyImageView( r->device, r->swapchainImageViews[i], nullptr );
                r->swapchainImageViews[i] = VK_NULL_HANDLE;
            }
        }
        r->swapchainImageCount = 0;

        DestroyDepthResources( r );

        if( r->swapchain != VK_NULL_HANDLE ) {
            vkDestroySwapchainKHR( r->device, r->swapchain, nullptr );
            r->swapchain = VK_NULL_HANDLE;
        }
    }

    static bool RecreateSwapchain( Renderer * r ) {
        VkSurfaceCapabilitiesKHR caps = {};
        VK_CHECK( vkGetPhysicalDeviceSurfaceCapabilitiesKHR( r->physicalDevice, r->surface, &caps ) );

        // A minimised window has a zero-sized surface, which is not a legal
        // swapchain extent. Stay resized so the next frame tries again.
        VkExtent2D extent = ChooseExtent( caps, r );
        if( extent.width == 0 || extent.height == 0 ) {
            r->framebufferResized = true;
            return true;
        }

        vkDeviceWaitIdle( r->device );
        DestroySwapchain( r );

        return CreateSwapchain( r ) &&
               CreateDepthResources( r ) &&
               CreateFramebuffers( r ) &&
               CreatePerImageSemaphores( r );
    }

    static bool CreateShaderModule( Renderer * r, const u32 * code, u64 byteCount,
                                    VkShaderModule * outModule ) {
        VkShaderModuleCreateInfo createInfo = {};
        createInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        createInfo.codeSize = byteCount;
        createInfo.pCode = code;
        VK_CHECK( vkCreateShaderModule( r->device, &createInfo, nullptr, outModule ) );
        return true;
    }

    static bool CreateTextureSetLayout( Renderer * r ) {
        VkDescriptorSetLayoutBinding binding = {};
        binding.binding = 0;
        binding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        binding.descriptorCount = 1;
        binding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

        VkDescriptorSetLayoutCreateInfo layoutInfo = {};
        layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        layoutInfo.bindingCount = 1;
        layoutInfo.pBindings = &binding;
        VK_CHECK( vkCreateDescriptorSetLayout( r->device, &layoutInfo, nullptr, &r->textureSetLayout ) );
        return true;
    }

    // Sized generously relative to what this renderer currently loads; a real
    // asset system would grow this or suballocate per batch of textures.
    constexpr u32 kMaxDescriptorSets = 256;

    static bool CreateDescriptorPool( Renderer * r ) {
        VkDescriptorPoolSize poolSize = {};
        poolSize.type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        poolSize.descriptorCount = kMaxDescriptorSets;

        VkDescriptorPoolCreateInfo poolInfo = {};
        poolInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        // Individually freeable, so destroying a texture hands its set back.
        // Without this, loading and dropping textures would walk through the
        // pool's budget and never get any of it back until shutdown.
        poolInfo.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
        poolInfo.maxSets = kMaxDescriptorSets;
        poolInfo.poolSizeCount = 1;
        poolInfo.pPoolSizes = &poolSize;
        VK_CHECK( vkCreateDescriptorPool( r->device, &poolInfo, nullptr, &r->descriptorPool ) );
        return true;
    }

    static bool CreateStaticMeshPipeline( Renderer * r ) {
        VkShaderModule vertModule = VK_NULL_HANDLE;
        VkShaderModule fragModule = VK_NULL_HANDLE;
        if( !CreateShaderModule( r, kStaticMeshVertSpv, sizeof( kStaticMeshVertSpv ), &vertModule ) ||
            !CreateShaderModule( r, kStaticMeshFragSpv, sizeof( kStaticMeshFragSpv ), &fragModule ) ) {
            return false;
        }

        VkPipelineShaderStageCreateInfo stages[2] = {};
        stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
        stages[0].module = vertModule;
        stages[0].pName = "main";
        stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
        stages[1].module = fragModule;
        stages[1].pName = "main";

        VkVertexInputBindingDescription binding = {};
        binding.binding = 0;
        binding.stride = (u32)sizeof( StaticMeshVertex );
        binding.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

        VkVertexInputAttributeDescription attributes[4] = {};
        attributes[0].location = 0;
        attributes[0].format = VK_FORMAT_R32G32B32_SFLOAT;
        attributes[0].offset = (u32)offsetof( StaticMeshVertex, position );
        attributes[1].location = 1;
        attributes[1].format = VK_FORMAT_R32G32B32_SFLOAT;
        attributes[1].offset = (u32)offsetof( StaticMeshVertex, normal );
        attributes[2].location = 2;
        attributes[2].format = VK_FORMAT_R32G32B32_SFLOAT;
        attributes[2].offset = (u32)offsetof( StaticMeshVertex, color );
        attributes[3].location = 3;
        attributes[3].format = VK_FORMAT_R32G32_SFLOAT;
        attributes[3].offset = (u32)offsetof( StaticMeshVertex, uv );

        VkPipelineVertexInputStateCreateInfo vertexInput = {};
        vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
        vertexInput.vertexBindingDescriptionCount = 1;
        vertexInput.pVertexBindingDescriptions = &binding;
        vertexInput.vertexAttributeDescriptionCount = (u32)SPLATS_ARRAY_COUNT( attributes );
        vertexInput.pVertexAttributeDescriptions = attributes;

        VkPipelineInputAssemblyStateCreateInfo inputAssembly = {};
        inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
        inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

        // Counts only: the actual viewport and scissor are set per frame, so a
        // resize never has to rebuild the pipeline.
        VkPipelineViewportStateCreateInfo viewportState = {};
        viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
        viewportState.viewportCount = 1;
        viewportState.scissorCount = 1;

        VkPipelineRasterizationStateCreateInfo raster = {};
        raster.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
        raster.polygonMode = VK_POLYGON_MODE_FILL;
        // The viewport is flipped to put +y up, which reverses winding on screen.
        // Culling stays off until there is geometry whose winding is trusted.
        raster.cullMode = VK_CULL_MODE_NONE;
        raster.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
        raster.lineWidth = 1.0f;

        VkPipelineMultisampleStateCreateInfo multisample = {};
        multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
        multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

        VkPipelineColorBlendAttachmentState blendAttachment = {};
        blendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

        VkPipelineColorBlendStateCreateInfo blend = {};
        blend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
        blend.attachmentCount = 1;
        blend.pAttachments = &blendAttachment;

        // Nearer fragments win. Depth goes into [0,1] with 0 at the near plane,
        // so the test is LESS rather than GREATER.
        VkPipelineDepthStencilStateCreateInfo depthStencil = {};
        depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
        depthStencil.depthTestEnable = VK_TRUE;
        depthStencil.depthWriteEnable = VK_TRUE;
        depthStencil.depthCompareOp = VK_COMPARE_OP_LESS;
        depthStencil.depthBoundsTestEnable = VK_FALSE;
        depthStencil.stencilTestEnable = VK_FALSE;
        depthStencil.minDepthBounds = 0.0f;
        depthStencil.maxDepthBounds = 1.0f;

        VkDynamicState dynamicStates[] = { VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR };
        VkPipelineDynamicStateCreateInfo dynamic = {};
        dynamic.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
        dynamic.dynamicStateCount = (u32)SPLATS_ARRAY_COUNT( dynamicStates );
        dynamic.pDynamicStates = dynamicStates;

        // Both stages: the vertex shader reads the matrix and the fragment
        // shader reads the tint, and one range has to cover the whole block.
        VkPushConstantRange pushRange = {};
        pushRange.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
        pushRange.offset = 0;
        pushRange.size = (u32)sizeof( StaticMeshPush );

        VkPipelineLayoutCreateInfo layoutInfo = {};
        layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        layoutInfo.setLayoutCount = 1;
        layoutInfo.pSetLayouts = &r->textureSetLayout;
        layoutInfo.pushConstantRangeCount = 1;
        layoutInfo.pPushConstantRanges = &pushRange;

        bool ok = vkCreatePipelineLayout( r->device, &layoutInfo, nullptr,
                                          &r->staticMeshPipelineLayout ) == VK_SUCCESS;
        if( ok ) {
            VkGraphicsPipelineCreateInfo pipelineInfo = {};
            pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
            pipelineInfo.stageCount = (u32)SPLATS_ARRAY_COUNT( stages );
            pipelineInfo.pStages = stages;
            pipelineInfo.pVertexInputState = &vertexInput;
            pipelineInfo.pInputAssemblyState = &inputAssembly;
            pipelineInfo.pViewportState = &viewportState;
            pipelineInfo.pRasterizationState = &raster;
            pipelineInfo.pMultisampleState = &multisample;
            pipelineInfo.pDepthStencilState = &depthStencil;
            pipelineInfo.pColorBlendState = &blend;
            pipelineInfo.pDynamicState = &dynamic;
            pipelineInfo.layout = r->staticMeshPipelineLayout;
            pipelineInfo.renderPass = r->renderPass;
            pipelineInfo.subpass = 0;

            ok = vkCreateGraphicsPipelines( r->device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr,
                                            &r->staticMeshPipeline ) == VK_SUCCESS;

            // The grid shares everything above and differs by exactly two
            // pieces of state, so it is a second pipeline off the same info
            // rather than a second shader pair. Depth writes are off so the
            // grid never occludes the geometry standing on it; the test stays
            // on so geometry in front still hides it.
            if( ok ) {
                inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_LINE_LIST;
                depthStencil.depthWriteEnable = VK_FALSE;
                ok = vkCreateGraphicsPipelines( r->device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr,
                                                &r->gridPipeline ) == VK_SUCCESS;
            }

            // The edit cage differs by one more piece of state: the depth test
            // goes off too. Its edges and handles sit exactly on the surface
            // they describe, which is the one case where an equal depth is
            // guaranteed rather than unlucky.
            if( ok ) {
                depthStencil.depthTestEnable = VK_FALSE;
                ok = vkCreateGraphicsPipelines( r->device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr,
                                                &r->editLinePipeline ) == VK_SUCCESS;
            }

            if( ok ) {
                inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_POINT_LIST;
                ok = vkCreateGraphicsPipelines( r->device, VK_NULL_HANDLE, 1, &pipelineInfo, nullptr,
                                                &r->editPointPipeline ) == VK_SUCCESS;
            }
        }

        // The modules are baked into the pipeline, so they go straight back.
        vkDestroyShaderModule( r->device, fragModule, nullptr );
        vkDestroyShaderModule( r->device, vertModule, nullptr );

        if( !ok ) {
            fprintf( stderr, "Failed to create the static mesh pipeline\n" );
        }
        return ok;
    }

    // VMA picks the memory type from the usage flags plus allocFlags, so callers
    // say what they intend to do with the buffer rather than naming heaps.
    // outInfo is optional; pass it to get pMappedData back for a mapped staging
    // allocation.
    static bool CreateBuffer( Renderer * r, u64 size, VkBufferUsageFlags usage,
                              VmaAllocationCreateFlags allocFlags, VkBuffer * outBuffer,
                              VmaAllocation * outAllocation, VmaAllocationInfo * outInfo ) {
        VkBufferCreateInfo bufferInfo = {};
        bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bufferInfo.size = size;
        bufferInfo.usage = usage;
        bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

        VmaAllocationCreateInfo allocInfo = {};
        allocInfo.usage = VMA_MEMORY_USAGE_AUTO;
        allocInfo.flags = allocFlags;

        VK_CHECK( vmaCreateBuffer( r->allocator, &bufferInfo, &allocInfo, outBuffer,
                                   outAllocation, outInfo ) );
        return true;
    }

    // Host-visible, already mapped, and written front to back exactly once.
    // Staging is the only host-writable memory this renderer asks for.
    constexpr VmaAllocationCreateFlags kStagingAllocFlags =
        VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT |
        VMA_ALLOCATION_CREATE_MAPPED_BIT;

    // Fills a freshly created staging allocation and makes the write visible to
    // the device. AUTO can land staging in non-coherent memory (device-local
    // host-visible on resizable BAR), so the flush is not optional; it is a
    // no-op when the memory turned out to be coherent after all.
    static bool WriteStaging( Renderer * r, const VmaAllocationInfo & info,
                              VmaAllocation allocation, const void * data, u64 size ) {
        if( info.pMappedData == nullptr ) {
            fprintf( stderr, "Staging allocation came back unmapped\n" );
            return false;
        }
        memcpy( info.pMappedData, data, (size_t)size );
        return vmaFlushAllocation( r->allocator, allocation, 0, size ) == VK_SUCCESS;
    }

    // One-shot command buffer pattern shared by every blocking upload below:
    // allocate, record, submit, wait, free. Fine for load-time work; nothing
    // here is meant for a per-frame streaming path.
    static bool BeginOneShotCommands( Renderer * r, VkCommandBuffer * outCmd ) {
        VkCommandBufferAllocateInfo allocInfo = {};
        allocInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        allocInfo.commandPool = r->commandPool;
        allocInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        allocInfo.commandBufferCount = 1;
        VK_CHECK( vkAllocateCommandBuffers( r->device, &allocInfo, outCmd ) );

        VkCommandBufferBeginInfo beginInfo = {};
        beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        VK_CHECK( vkBeginCommandBuffer( *outCmd, &beginInfo ) );
        return true;
    }

    static bool EndOneShotCommands( Renderer * r, VkCommandBuffer cmd ) {
        VK_CHECK( vkEndCommandBuffer( cmd ) );

        VkSubmitInfo submitInfo = {};
        submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
        submitInfo.commandBufferCount = 1;
        submitInfo.pCommandBuffers = &cmd;
        bool ok = vkQueueSubmit( r->graphicsQueue, 1, &submitInfo, VK_NULL_HANDLE ) == VK_SUCCESS;
        if( ok ) {
            vkQueueWaitIdle( r->graphicsQueue );
        }

        vkFreeCommandBuffers( r->device, r->commandPool, 1, &cmd );
        return ok;
    }

    // Stages through host-visible memory and blocks on the copy.
    static bool UploadBuffer( Renderer * r, VkBuffer dst, const void * data, u64 size ) {
        VkBuffer staging = VK_NULL_HANDLE;
        VmaAllocation stagingAllocation = VK_NULL_HANDLE;
        VmaAllocationInfo stagingInfo = {};
        if( !CreateBuffer( r, size, VK_BUFFER_USAGE_TRANSFER_SRC_BIT, kStagingAllocFlags,
                           &staging, &stagingAllocation, &stagingInfo ) ) {
            return false;
        }

        bool ok = WriteStaging( r, stagingInfo, stagingAllocation, data, size );

        VkCommandBuffer cmd = VK_NULL_HANDLE;
        if( ok ) {
            ok = BeginOneShotCommands( r, &cmd );
        }

        if( ok ) {
            VkBufferCopy region = {};
            region.size = size;
            vkCmdCopyBuffer( cmd, staging, dst, 1, &region );
            ok = EndOneShotCommands( r, cmd );
        }

        vmaDestroyBuffer( r->allocator, staging, stagingAllocation );

        if( !ok ) {
            fprintf( stderr, "Failed to upload %llu bytes\n", (unsigned long long)size );
        }
        return ok;
    }

    static bool CreateImage( Renderer * r, i32 width, i32 height, VkFormat format,
                             VkImageUsageFlags usage, VkImage * outImage,
                             VmaAllocation * outAllocation ) {
        VkImageCreateInfo imageInfo = {};
        imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
        imageInfo.imageType = VK_IMAGE_TYPE_2D;
        imageInfo.format = format;
        imageInfo.extent.width = (u32)width;
        imageInfo.extent.height = (u32)height;
        imageInfo.extent.depth = 1;
        imageInfo.mipLevels = 1;
        imageInfo.arrayLayers = 1;
        imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
        imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
        imageInfo.usage = usage;
        imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;

        VmaAllocationCreateInfo allocInfo = {};
        allocInfo.usage = VMA_MEMORY_USAGE_AUTO;
        allocInfo.requiredFlags = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
        VK_CHECK( vmaCreateImage( r->allocator, &imageInfo, &allocInfo, outImage,
                                  outAllocation, nullptr ) );
        return true;
    }

    // Only the two transitions the texture upload path actually needs; anything
    // else falls through to the error case rather than guessing stage masks.
    static bool TransitionImageLayout( Renderer * r, VkImage image,
                                       VkImageLayout oldLayout, VkImageLayout newLayout ) {
        VkCommandBuffer cmd = VK_NULL_HANDLE;
        if( !BeginOneShotCommands( r, &cmd ) ) {
            return false;
        }

        VkImageMemoryBarrier barrier = {};
        barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
        barrier.oldLayout = oldLayout;
        barrier.newLayout = newLayout;
        barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        barrier.image = image;
        barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        barrier.subresourceRange.levelCount = 1;
        barrier.subresourceRange.layerCount = 1;

        VkPipelineStageFlags srcStage = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
        VkPipelineStageFlags dstStage = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;

        if( oldLayout == VK_IMAGE_LAYOUT_UNDEFINED &&
            newLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL ) {
            barrier.srcAccessMask = 0;
            barrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
            srcStage = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
            dstStage = VK_PIPELINE_STAGE_TRANSFER_BIT;
        } else if( oldLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL &&
                   newLayout == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL ) {
            barrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
            barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
            srcStage = VK_PIPELINE_STAGE_TRANSFER_BIT;
            dstStage = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
        } else {
            fprintf( stderr, "Unsupported image layout transition\n" );
            vkFreeCommandBuffers( r->device, r->commandPool, 1, &cmd );
            return false;
        }

        vkCmdPipelineBarrier( cmd, srcStage, dstStage, 0, 0, nullptr, 0, nullptr, 1, &barrier );
        return EndOneShotCommands( r, cmd );
    }

    static bool CopyBufferToImage( Renderer * r, VkBuffer buffer, VkImage image, i32 width, i32 height ) {
        VkCommandBuffer cmd = VK_NULL_HANDLE;
        if( !BeginOneShotCommands( r, &cmd ) ) {
            return false;
        }

        VkBufferImageCopy region = {};
        region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        region.imageSubresource.layerCount = 1;
        region.imageExtent.width = (u32)width;
        region.imageExtent.height = (u32)height;
        region.imageExtent.depth = 1;

        vkCmdCopyBufferToImage( cmd, buffer, image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region );
        return EndOneShotCommands( r, cmd );
    }

    // Both halves of a texture's lifetime are internal now: the pool below is
    // the only thing that owns a RenderTexture, so callers get a handle rather
    // than a struct they would have to remember to destroy.
    static void RenderTextureDestroy( Renderer * r, RenderTexture * texture );

    static bool RenderTextureCreate( Renderer * r, const TextureAsset & asset, RenderTexture * outTexture ) {
        *outTexture = {};

        if( asset.width <= 0 || asset.height <= 0 ) {
            fprintf( stderr, "Texture asset has no pixels\n" );
            return false;
        }

        const VkFormat format = asset.meta.format == TextureFormat_RGBA8_SRGB
            ? VK_FORMAT_R8G8B8A8_SRGB
            : VK_FORMAT_R8G8B8A8_UNORM;

        if( !CreateImage( r, asset.width, asset.height, format,
                          VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
                          &outTexture->image, &outTexture->allocation ) ) {
            return false;
        }

        const u64 byteCount = (u64)asset.width * (u64)asset.height * 4;

        VkBuffer staging = VK_NULL_HANDLE;
        VmaAllocation stagingAllocation = VK_NULL_HANDLE;
        VmaAllocationInfo stagingInfo = {};
        bool ok = CreateBuffer( r, byteCount, VK_BUFFER_USAGE_TRANSFER_SRC_BIT, kStagingAllocFlags,
                                &staging, &stagingAllocation, &stagingInfo );
        if( ok ) {
            ok = WriteStaging( r, stagingInfo, stagingAllocation, asset.pixels.data, byteCount );
        }

        ok = ok && TransitionImageLayout( r, outTexture->image, VK_IMAGE_LAYOUT_UNDEFINED,
                                          VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL );
        ok = ok && CopyBufferToImage( r, staging, outTexture->image, asset.width, asset.height );
        ok = ok && TransitionImageLayout( r, outTexture->image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                                          VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL );

        if( staging != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, staging, stagingAllocation );
        }

        if( !ok ) {
            RenderTextureDestroy( r, outTexture );
            return false;
        }

        VkImageViewCreateInfo viewInfo = {};
        viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
        viewInfo.image = outTexture->image;
        viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
        viewInfo.format = format;
        viewInfo.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        viewInfo.subresourceRange.levelCount = 1;
        viewInfo.subresourceRange.layerCount = 1;
        if( vkCreateImageView( r->device, &viewInfo, nullptr, &outTexture->view ) != VK_SUCCESS ) {
            RenderTextureDestroy( r, outTexture );
            return false;
        }

        const VkFilter filter = asset.meta.filter == TextureFilter_Linear
            ? VK_FILTER_LINEAR
            : VK_FILTER_NEAREST;

        VkSamplerAddressMode addressMode = VK_SAMPLER_ADDRESS_MODE_REPEAT;
        if( asset.meta.wrap == TextureWrap_Clamp ) {
            addressMode = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        } else if( asset.meta.wrap == TextureWrap_Mirror ) {
            addressMode = VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT;
        }

        VkSamplerCreateInfo samplerInfo = {};
        samplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
        samplerInfo.magFilter = filter;
        samplerInfo.minFilter = filter;
        samplerInfo.addressModeU = addressMode;
        samplerInfo.addressModeV = addressMode;
        samplerInfo.addressModeW = addressMode;
        // The device is created with no features enabled, so anisotropic
        // filtering is not available - leave it off rather than request it.
        samplerInfo.anisotropyEnable = VK_FALSE;
        samplerInfo.maxAnisotropy = 1.0f;
        samplerInfo.borderColor = VK_BORDER_COLOR_INT_OPAQUE_BLACK;
        samplerInfo.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
        if( vkCreateSampler( r->device, &samplerInfo, nullptr, &outTexture->sampler ) != VK_SUCCESS ) {
            RenderTextureDestroy( r, outTexture );
            return false;
        }

        VkDescriptorSetAllocateInfo setAllocInfo = {};
        setAllocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        setAllocInfo.descriptorPool = r->descriptorPool;
        setAllocInfo.descriptorSetCount = 1;
        setAllocInfo.pSetLayouts = &r->textureSetLayout;
        if( vkAllocateDescriptorSets( r->device, &setAllocInfo, &outTexture->descriptorSet ) != VK_SUCCESS ) {
            RenderTextureDestroy( r, outTexture );
            return false;
        }

        VkDescriptorImageInfo descriptorImageInfo = {};
        descriptorImageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
        descriptorImageInfo.imageView = outTexture->view;
        descriptorImageInfo.sampler = outTexture->sampler;

        VkWriteDescriptorSet write = {};
        write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write.dstSet = outTexture->descriptorSet;
        write.dstBinding = 0;
        write.descriptorCount = 1;
        write.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        write.pImageInfo = &descriptorImageInfo;
        vkUpdateDescriptorSets( r->device, 1, &write, 0, nullptr );

        outTexture->width = asset.width;
        outTexture->height = asset.height;
        return true;
    }

    static void RenderTextureDestroy( Renderer * r, RenderTexture * texture ) {
        if( r->device == VK_NULL_HANDLE ) {
            return;
        }

        // The pool carries VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT,
        // so the set goes back here rather than waiting for the pool itself to
        // be destroyed at shutdown.
        if( texture->descriptorSet != VK_NULL_HANDLE && r->descriptorPool != VK_NULL_HANDLE ) {
            vkFreeDescriptorSets( r->device, r->descriptorPool, 1, &texture->descriptorSet );
        }
        if( texture->sampler != VK_NULL_HANDLE ) {
            vkDestroySampler( r->device, texture->sampler, nullptr );
        }
        if( texture->view != VK_NULL_HANDLE ) {
            vkDestroyImageView( r->device, texture->view, nullptr );
        }
        if( texture->image != VK_NULL_HANDLE ) {
            vmaDestroyImage( r->allocator, texture->image, texture->allocation );
        }

        *texture = {};
    }

    RenderTextureHandle RendererCreateTexture( Renderer * r, const TextureAsset & asset ) {
        RenderTexture texture = {};
        if( !RenderTextureCreate( r, asset, &texture ) ) {
            return {};
        }

        RenderTextureHandle handle = PoolAdd( r->textures, texture );
        if( HandleIsNull( handle ) ) {
            // Nothing can name it, so it would leak until shutdown otherwise.
            RenderTextureDestroy( r, &texture );
        }
        return handle;
    }

    void RendererDestroyTexture( Renderer * r, RenderTextureHandle handle ) {
        RenderTexture * texture = PoolGet( r->textures, handle );
        if( texture == nullptr ) {
            return;
        }

        // A frame still in flight may be sampling this image.
        vkDeviceWaitIdle( r->device );
        RenderTextureDestroy( r, texture );
        PoolRemove( r->textures, handle );
    }

    const RenderTexture * RendererGetTexture( const Renderer * r, RenderTextureHandle handle ) {
        return PoolGet( r->textures, handle );
    }

    static bool CreateWhiteTexture( Renderer * r ) {
        u8 pixel[4] = { 255, 255, 255, 255 };

        TextureAsset asset = {};
        asset.width = 1;
        asset.height = 1;
        asset.meta.format = TextureFormat_RGBA8_UNORM;
        asset.meta.filter = TextureFilter_Nearest;
        asset.meta.wrap = TextureWrap_Repeat;
        ListAddRange( asset.pixels, pixel, (i32)SPLATS_ARRAY_COUNT( pixel ) );

        r->whiteTexture = RendererCreateTexture( r, asset );
        ListFree( asset.pixels );
        return !HandleIsNull( r->whiteTexture );
    }

    // Vertex handles in pixels. Big enough to hit with a cursor, small enough
    // not to bury the geometry underneath them.
    constexpr f32 kEditPointSize = 7.0f;

    // Lines either side of the origin per axis. Held constant while the spacing
    // changes, so the grid covers more ground as it coarsens rather than piling
    // up more lines than the screen can resolve.
    constexpr i32 kGridHalfLines = 50;
    constexpr f32 kGridDefaultSpacing = 1.0f;
    // Every tenth line is brighter, the way a ruled sheet marks its decades.
    constexpr i32 kGridMajorEvery = 10;

    static void GridPushLine( List<StaticMeshVertex> & vertices, Vec3 a, Vec3 b, Vec3 color ) {
        StaticMeshVertex vertex = {};
        vertex.normal = Vec3{ 0.0f, 1.0f, 0.0f };
        vertex.color = color;
        // Sampled against the white 1x1 fallback, so any uv gives the same
        // texel and the vertex colour comes through unmodified.
        vertex.uv = Vec2{ 0.0f, 0.0f };

        vertex.position = a;
        ListAdd( vertices, vertex );
        vertex.position = b;
        ListAdd( vertices, vertex );
    }

    // Built in the grid's own space - the xz plane, centred on the origin -
    // never in world space. RendererSetGridTransform is what puts it somewhere,
    // so a grid that is re-aimed or moved costs nothing beyond a push constant.
    static bool CreateGrid( Renderer * r, f32 spacing ) {
        const Vec3 minorColor = { 0.28f, 0.28f, 0.32f };
        const Vec3 majorColor = { 0.42f, 0.42f, 0.48f };
        // The two lines through the grid's own origin, marking its u and v axes.
        // On an unmoved grid they land on the world x and z axes, which is
        // where the colours come from.
        const Vec3 axisXColor = { 0.75f, 0.25f, 0.30f };
        const Vec3 axisZColor = { 0.25f, 0.45f, 0.80f };

        List<StaticMeshVertex> vertices = {};
        const i32 lineCount = kGridHalfLines;
        const f32 kGridExtent = (f32)kGridHalfLines * spacing;

        for( i32 i = -lineCount; i <= lineCount; i++ ) {
            const f32 offset = (f32)i * spacing;
            const bool major = ( i % kGridMajorEvery ) == 0;

            // Running along z, stepped across x. The one at x = 0 is the z axis.
            const Vec3 zColor = i == 0 ? axisZColor : ( major ? majorColor : minorColor );
            GridPushLine( vertices, Vec3{ offset, 0.0f, -kGridExtent },
                          Vec3{ offset, 0.0f, kGridExtent }, zColor );

            // Running along x, stepped across z. The one at z = 0 is the x axis.
            const Vec3 xColor = i == 0 ? axisXColor : ( major ? majorColor : minorColor );
            GridPushLine( vertices, Vec3{ -kGridExtent, 0.0f, offset },
                          Vec3{ kGridExtent, 0.0f, offset }, xColor );
        }

        const u64 byteCount = (u64)vertices.count * sizeof( StaticMeshVertex );
        bool ok = CreateBuffer( r, byteCount,
                                VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT, 0,
                                &r->gridVertexBuffer, &r->gridVertexAllocation, nullptr );
        ok = ok && UploadBuffer( r, r->gridVertexBuffer, vertices.data, byteCount );
        if( ok ) {
            r->gridVertexCount = vertices.count;
            r->gridVisible = true;
            r->gridSpacing = spacing;
        } else {
            fprintf( stderr, "Failed to build the grid\n" );
        }

        ListFree( vertices );
        return ok;
    }

    // How many pixels thick the mode border is. Drawn as that many concentric
    // rectangles one pixel apart rather than as a wide line: wideLines is an
    // optional device feature, and a one-pixel line is the only width Vulkan
    // guarantees.
    constexpr i32 kBorderThickness = 3;

    // A unit rectangle in clip space as four lines, which is what lets the
    // border be drawn with no camera and survive a resize untouched. The
    // colour is white so the tint carries the mode's colour whole.
    static bool CreateBorder( Renderer * r ) {
        const Vec3 corners[] = {
            { -1.0f, -1.0f, 0.0f },
            {  1.0f, -1.0f, 0.0f },
            {  1.0f,  1.0f, 0.0f },
            { -1.0f,  1.0f, 0.0f },
        };

        constexpr i32 kCornerCount = (i32)SPLATS_ARRAY_COUNT( corners );
        List<StaticMeshVertex> vertices = {};
        for( i32 i = 0; i < kCornerCount; i++ ) {
            GridPushLine( vertices, corners[i], corners[( i + 1 ) % kCornerCount],
                          Vec3{ 1.0f, 1.0f, 1.0f } );
        }

        const u64 byteCount = (u64)vertices.count * sizeof( StaticMeshVertex );
        bool ok = CreateBuffer( r, byteCount,
                                VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT, 0,
                                &r->borderVertexBuffer, &r->borderVertexAllocation, nullptr );
        ok = ok && UploadBuffer( r, r->borderVertexBuffer, vertices.data, byteCount );
        if( ok ) {
            r->borderVertexCount = vertices.count;
        } else {
            fprintf( stderr, "Failed to build the viewport border\n" );
        }

        ListFree( vertices );
        return ok;
    }

    static void RenderStaticMeshDestroy( Renderer * r, RenderStaticMesh * mesh );

    static bool RenderStaticMeshCreate( Renderer * r,
                                        const StaticMeshVertex * vertices, i32 vertexCount,
                                        const u32 * indices, i32 indexCount,
                                        RenderTextureHandle texture,
                                        RenderStaticMesh * outMesh ) {
        *outMesh = {};
        outMesh->transform = Mat4Identity();
        outMesh->tint = kNoTint;
        // A null handle here is fine: the draw path resolves it to the white
        // 1x1 fallback, which is what keeps the descriptor populated.
        outMesh->texture = texture;

        if( vertexCount <= 0 || indexCount <= 0 ) {
            fprintf( stderr, "Static mesh needs both vertices and indices\n" );
            return false;
        }

        u64 vertexBytes = (u64)vertexCount * sizeof( StaticMeshVertex );
        u64 indexBytes = (u64)indexCount * sizeof( u32 );

        // No host access flag, so VMA puts both of these in device-local memory
        // and they are filled through the staging path below.
        if( !CreateBuffer( r, vertexBytes,
                           VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT, 0,
                           &outMesh->vertexBuffer, &outMesh->vertexAllocation, nullptr ) ) {
            return false;
        }

        if( !CreateBuffer( r, indexBytes,
                           VK_BUFFER_USAGE_INDEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT, 0,
                           &outMesh->indexBuffer, &outMesh->indexAllocation, nullptr ) ) {
            RenderStaticMeshDestroy( r, outMesh );
            return false;
        }

        if( !UploadBuffer( r, outMesh->vertexBuffer, vertices, vertexBytes ) ||
            !UploadBuffer( r, outMesh->indexBuffer, indices, indexBytes ) ) {
            RenderStaticMeshDestroy( r, outMesh );
            return false;
        }

        outMesh->vertexCount = vertexCount;
        outMesh->indexCount = indexCount;
        return true;
    }

    static void RenderStaticMeshDestroy( Renderer * r, RenderStaticMesh * mesh ) {
        if( r->device == VK_NULL_HANDLE ) {
            return;
        }

        if( mesh->vertexBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, mesh->vertexBuffer, mesh->vertexAllocation );
        }
        if( mesh->indexBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, mesh->indexBuffer, mesh->indexAllocation );
        }

        *mesh = {};
    }

    RenderMeshHandle RendererCreateStaticMesh( Renderer * r,
                                               const StaticMeshVertex * vertices, i32 vertexCount,
                                               const u32 * indices, i32 indexCount,
                                               RenderTextureHandle texture ) {
        RenderStaticMesh mesh = {};
        if( !RenderStaticMeshCreate( r, vertices, vertexCount, indices, indexCount, texture, &mesh ) ) {
            return {};
        }

        RenderMeshHandle handle = PoolAdd( r->staticMeshes, mesh );
        if( HandleIsNull( handle ) ) {
            RenderStaticMeshDestroy( r, &mesh );
        }
        return handle;
    }

    void RendererDestroyStaticMesh( Renderer * r, RenderMeshHandle handle ) {
        RenderStaticMesh * mesh = PoolGet( r->staticMeshes, handle );
        if( mesh == nullptr ) {
            return;
        }

        // The buffers about to go back may still be referenced by a frame the
        // GPU has not finished with.
        vkDeviceWaitIdle( r->device );
        RenderStaticMeshDestroy( r, mesh );
        PoolRemove( r->staticMeshes, handle );
    }

    RenderStaticMesh * RendererGetStaticMesh( Renderer * r, RenderMeshHandle handle ) {
        return PoolGet( r->staticMeshes, handle );
    }

    bool RendererAddDebugTriangle( Renderer * r ) {
        // Counter-clockwise with +y up, sitting on the near plane. UVs are
        // arbitrary here since these bind the white fallback texture, but they
        // are filled in sanely rather than left at zero.
        const StaticMeshVertex vertices[] = {
            { {  0.0f,  0.5f, 0.0f }, { 0.0f, 0.0f, 1.0f }, { 1.0f, 0.0f, 0.0f }, { 0.5f, 0.0f } },
            { { -0.5f, -0.5f, 0.0f }, { 0.0f, 0.0f, 1.0f }, { 0.0f, 1.0f, 0.0f }, { 0.0f, 1.0f } },
            { {  0.5f, -0.5f, 0.0f }, { 0.0f, 0.0f, 1.0f }, { 0.0f, 0.0f, 1.0f }, { 1.0f, 1.0f } },
        };
        const u32 indices[] = { 0, 1, 2 };

        // Two of them, the second offset and further away, submitted after the
        // near one. Without a depth buffer the far triangle paints over the near
        // one where they overlap, so this doubles as the test that depth works.
        const Vec3 offsets[] = {
            { 0.0f, 0.0f, 0.0f },
            { 0.45f, -0.15f, -0.6f },
        };

        for( u64 i = 0; i < SPLATS_ARRAY_COUNT( offsets ); i++ ) {
            RenderMeshHandle handle = RendererCreateStaticMesh(
                r, vertices, (i32)SPLATS_ARRAY_COUNT( vertices ),
                indices, (i32)SPLATS_ARRAY_COUNT( indices ), {} );

            RenderStaticMesh * mesh = RendererGetStaticMesh( r, handle );
            if( mesh == nullptr ) {
                return false;
            }

            mesh->transform = Mat4Identity();
            mesh->transform.m[0][3] = offsets[i].x;
            mesh->transform.m[1][3] = offsets[i].y;
            mesh->transform.m[2][3] = offsets[i].z;
        }
        return true;
    }

    bool RendererAddTexturedPlane( Renderer * r, RenderTextureHandle texture, Vec3 center, f32 size ) {
        const f32 half = size * 0.5f;
        const Vec3 white = { 1.0f, 1.0f, 1.0f };
        const Vec3 normal = { 0.0f, 0.0f, 1.0f };

        // CCW as seen from +z, which is where the plane's normal points.
        const StaticMeshVertex vertices[] = {
            { { center.x - half, center.y - half, center.z }, normal, white, { 0.0f, 0.0f } },
            { { center.x + half, center.y - half, center.z }, normal, white, { 1.0f, 0.0f } },
            { { center.x + half, center.y + half, center.z }, normal, white, { 1.0f, 1.0f } },
            { { center.x - half, center.y + half, center.z }, normal, white, { 0.0f, 1.0f } },
        };
        const u32 indices[] = { 0, 1, 2, 0, 2, 3 };

        RenderMeshHandle handle = RendererCreateStaticMesh(
            r, vertices, (i32)SPLATS_ARRAY_COUNT( vertices ),
            indices, (i32)SPLATS_ARRAY_COUNT( indices ), texture );
        return !HandleIsNull( handle );
    }

    static bool RecordCommandBuffer( Renderer * r, VkCommandBuffer cmd, i32 imageIndex ) {
        // The grid binds this, and so does every mesh whose texture handle is
        // null or stale. Startup fails without it, so losing it is a
        // should-never-happen - but the alternative to checking is binding a
        // null descriptor set, which is a device loss rather than a blank frame.
        const RenderTexture * white = PoolGet( r->textures, r->whiteTexture );
        if( white == nullptr ) {
            return false;
        }
        const VkDescriptorSet whiteSet = white->descriptorSet;

        VkCommandBufferBeginInfo beginInfo = {};
        beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        VK_CHECK( vkBeginCommandBuffer( cmd, &beginInfo ) );

        VkRenderPassBeginInfo passInfo = {};
        passInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
        passInfo.renderPass = r->renderPass;
        passInfo.framebuffer = r->framebuffers[imageIndex];
        passInfo.renderArea.extent = r->swapchainExtent;
        // Indices match the render pass attachment order: colour, then depth.
        // Depth clears to the far plane, which is 1.0 in Vulkan's [0,1] range.
        VkClearValue clearValues[2] = {};
        clearValues[0] = kClearColor;
        clearValues[1].depthStencil.depth = 1.0f;

        passInfo.clearValueCount = (u32)SPLATS_ARRAY_COUNT( clearValues );
        passInfo.pClearValues = clearValues;

        vkCmdBeginRenderPass( cmd, &passInfo, VK_SUBPASS_CONTENTS_INLINE );

        const f32 surfaceWidth = (f32)r->swapchainExtent.width;
        const f32 surfaceHeight = (f32)r->swapchainExtent.height;

        for( i32 v = 0; v < r->viewCount; v++ ) {
            const RenderView & view = r->views[v];

            // Rounded out to whole pixels here rather than stored that way, so
            // a resize does not have to revisit the layout.
            const f32 rectX = view.x * surfaceWidth;
            const f32 rectY = view.y * surfaceHeight;
            const f32 rectWidth = view.width * surfaceWidth;
            const f32 rectHeight = view.height * surfaceHeight;

            // A collapsed pane is not a legal viewport, and there is nothing to
            // see in it anyway.
            if( rectWidth < 1.0f || rectHeight < 1.0f ) {
                continue;
            }

            // Negative height flips clip space so +y is up, matching the camera
            // convention in sol_math.h. Core since Vulkan 1.1. The flip pins the
            // viewport to the bottom of its rect, hence the + rectHeight.
            VkViewport viewport = {};
            viewport.x = rectX;
            viewport.y = rectY + rectHeight;
            viewport.width = rectWidth;
            viewport.height = -rectHeight;
            viewport.minDepth = 0.0f;
            viewport.maxDepth = 1.0f;
            vkCmdSetViewport( cmd, 0, 1, &viewport );

            // Clipped to the surface: a rounded-up rect on the right or bottom
            // edge would otherwise run a pixel past the attachment.
            VkRect2D scissor = {};
            scissor.offset.x = (i32)rectX;
            scissor.offset.y = (i32)rectY;
            scissor.extent.width = (u32)rectWidth;
            scissor.extent.height = (u32)rectHeight;
            if( scissor.offset.x + (i32)scissor.extent.width > (i32)r->swapchainExtent.width ) {
                scissor.extent.width = r->swapchainExtent.width - (u32)scissor.offset.x;
            }
            if( scissor.offset.y + (i32)scissor.extent.height > (i32)r->swapchainExtent.height ) {
                scissor.extent.height = r->swapchainExtent.height - (u32)scissor.offset.y;
            }
            vkCmdSetScissor( cmd, 0, 1, &scissor );

            // Grid first. It writes no depth, so drawing it before the meshes
            // is what lets them paint over it rather than the reverse.
            if( r->gridVisible && r->gridVertexCount > 0 ) {
                vkCmdBindPipeline( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->gridPipeline );

                // The grid is authored on its own xz plane, so its transform
                // is the model half of the mvp. The whole block goes every
                // time: pushing only part of it would leave the fragment
                // shader reading bytes nothing ever wrote.
                StaticMeshPush gridPush = {};
                gridPush.mvp = view.viewProjection * r->gridTransform;
                gridPush.tint = kNoTint;
                gridPush.pointSize = 1.0f;
                vkCmdPushConstants( cmd, r->staticMeshPipelineLayout,
                                    VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                                    0, (u32)sizeof( gridPush ), &gridPush );
                vkCmdBindDescriptorSets( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->staticMeshPipelineLayout,
                                         0, 1, &whiteSet, 0, nullptr );

                VkDeviceSize gridOffset = 0;
                vkCmdBindVertexBuffers( cmd, 0, 1, &r->gridVertexBuffer, &gridOffset );
                vkCmdDraw( cmd, (u32)r->gridVertexCount, 1, 0, 0 );
            }

            vkCmdBindPipeline( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->staticMeshPipeline );

            // Slots, not elements: the pool leaves holes where meshes were
            // destroyed, and PoolAt is what tells the two apart.
            for( i32 i = 0; i < PoolSlotCount( r->staticMeshes ); i++ ) {
                const RenderStaticMesh * mesh = PoolAt( r->staticMeshes, i );
                if( mesh == nullptr ) {
                    continue;
                }

                StaticMeshPush push = {};
                push.mvp = view.viewProjection * mesh->transform;
                push.tint = mesh->tint;
                push.pointSize = 1.0f;
                vkCmdPushConstants( cmd, r->staticMeshPipelineLayout,
                                    VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                                    0, (u32)sizeof( push ), &push );

                // Resolved per draw, so a mesh whose texture was destroyed
                // falls back to white instead of binding a freed set.
                const RenderTexture * texture = PoolGet( r->textures, mesh->texture );
                const VkDescriptorSet meshSet = texture != nullptr ? texture->descriptorSet : whiteSet;
                vkCmdBindDescriptorSets( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->staticMeshPipelineLayout,
                                         0, 1, &meshSet, 0, nullptr );

                VkDeviceSize offset = 0;
                vkCmdBindVertexBuffers( cmd, 0, 1, &mesh->vertexBuffer, &offset );
                vkCmdBindIndexBuffer( cmd, mesh->indexBuffer, 0, VK_INDEX_TYPE_UINT32 );
                vkCmdDrawIndexed( cmd, (u32)mesh->indexCount, 1, 0, 0, 0 );
            }

            // Last in the view, with the depth test off in both cage pipelines,
            // so the edges and handles land on top of the shape they describe.
            if( r->editOverlay.visible ) {
                StaticMeshPush editPush = {};
                editPush.mvp = view.viewProjection * r->editOverlay.transform;
                editPush.tint = kNoTint;
                editPush.pointSize = r->largePoints ? kEditPointSize : 1.0f;
                vkCmdPushConstants( cmd, r->staticMeshPipelineLayout,
                                    VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                                    0, (u32)sizeof( editPush ), &editPush );

                // The cage samples the white fallback, so its vertex colours
                // come through as written.
                vkCmdBindDescriptorSets( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->staticMeshPipelineLayout,
                                         0, 1, &whiteSet, 0, nullptr );

                VkDeviceSize editOffset = 0;
                if( r->editOverlay.lineVertexCount > 0 ) {
                    vkCmdBindPipeline( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->editLinePipeline );
                    vkCmdBindVertexBuffers( cmd, 0, 1, &r->editOverlay.lineBuffer, &editOffset );
                    vkCmdDraw( cmd, (u32)r->editOverlay.lineVertexCount, 1, 0, 0 );
                }

                if( r->editOverlay.pointVertexCount > 0 ) {
                    vkCmdBindPipeline( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->editPointPipeline );
                    vkCmdBindVertexBuffers( cmd, 0, 1, &r->editOverlay.pointBuffer, &editOffset );
                    vkCmdDraw( cmd, (u32)r->editOverlay.pointVertexCount, 1, 0, 0 );
                }
            }

            // One draw per range so each handle can carry its own tint, which
            // is what lets the hovered axis light up without a second buffer.
            if( r->gizmoVisible && r->gizmoVertexCount > 0 ) {
                vkCmdBindPipeline( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->editLinePipeline );
                vkCmdBindDescriptorSets( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->staticMeshPipelineLayout,
                                         0, 1, &whiteSet, 0, nullptr );

                VkDeviceSize gizmoOffset = 0;
                vkCmdBindVertexBuffers( cmd, 0, 1, &r->gizmoVertexBuffer, &gizmoOffset );

                for( i32 g = 0; g < r->gizmoRangeCount; g++ ) {
                    const RenderGizmoRange & range = r->gizmoRanges[g];
                    if( range.vertexCount <= 0 ) {
                        continue;
                    }

                    StaticMeshPush gizmoPush = {};
                    gizmoPush.mvp = view.viewProjection * r->gizmoTransform;
                    gizmoPush.tint = range.tint;
                    gizmoPush.pointSize = 1.0f;
                    vkCmdPushConstants( cmd, r->staticMeshPipelineLayout,
                                        VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                                        0, (u32)sizeof( gizmoPush ), &gizmoPush );
                    vkCmdDraw( cmd, (u32)range.vertexCount, 1, (u32)range.firstVertex, 0 );
                }
            }
        }

        // Over every view and outside the loop: the border frames the whole
        // surface, not each pane, so it takes the surface's own viewport back
        // from whichever view set one last. The line pipeline has the depth
        // test off, so nothing drawn above can bury it.
        if( r->borderVisible && r->borderVertexCount > 0 ) {
            VkViewport full = {};
            full.x = 0.0f;
            full.y = surfaceHeight;
            full.width = surfaceWidth;
            full.height = -surfaceHeight;
            full.minDepth = 0.0f;
            full.maxDepth = 1.0f;
            vkCmdSetViewport( cmd, 0, 1, &full );

            VkRect2D fullScissor = {};
            fullScissor.extent = r->swapchainExtent;
            vkCmdSetScissor( cmd, 0, 1, &fullScissor );

            vkCmdBindPipeline( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->editLinePipeline );
            vkCmdBindDescriptorSets( cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, r->staticMeshPipelineLayout,
                                     0, 1, &whiteSet, 0, nullptr );

            VkDeviceSize borderOffset = 0;
            vkCmdBindVertexBuffers( cmd, 0, 1, &r->borderVertexBuffer, &borderOffset );

            for( i32 i = 0; i < kBorderThickness; i++ ) {
                // Ring i sits on pixel i in from the edge. A rectangle left at
                // the clip-space edge would land half off the attachment, hence
                // the half-pixel: 2 / extent is one pixel in clip space.
                const f32 inset = (f32)( 2 * i + 1 );
                StaticMeshPush borderPush = {};
                borderPush.mvp = Mat4Scale( Vec3{ 1.0f - inset / surfaceWidth,
                                                  1.0f - inset / surfaceHeight,
                                                  1.0f } );
                borderPush.tint = Vec4{ r->borderColor.x, r->borderColor.y, r->borderColor.z, 1.0f };
                borderPush.pointSize = 1.0f;
                vkCmdPushConstants( cmd, r->staticMeshPipelineLayout,
                                    VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                                    0, (u32)sizeof( borderPush ), &borderPush );
                vkCmdDraw( cmd, (u32)r->borderVertexCount, 1, 0, 0 );
            }
        }

        vkCmdEndRenderPass( cmd );

        VK_CHECK( vkEndCommandBuffer( cmd ) );
        return true;
    }

    bool RendererCreateInstance( Renderer * r, const char * const * requiredExtensions,
                                 u32 requiredCount ) {
        *r = {};

        bool useValidation = kEnableValidation && HasValidationLayer();
        if( kEnableValidation && !useValidation ) {
            printf( "Validation layers requested but not available, continuing without\n" );
        }
        return CreateInstance( r, requiredExtensions, requiredCount, useValidation );
    }

    bool RendererStartup( Renderer * r, VkSurfaceKHR surface, bool ownsSurface,
                          i32 width, i32 height ) {
        r->surface = surface;
        r->ownsSurface = ownsSurface;
        r->fallbackWidth = width;
        r->fallbackHeight = height;
        RendererSetViewProjection( r, Mat4Identity() );
        // A zeroed Mat4 would collapse the grid to a point, so the identity has
        // to be there before the first frame whether anyone re-aims it or not.
        RendererSetGridTransform( r, Mat4Identity() );

        return PickPhysicalDevice( r ) &&
               CreateLogicalDevice( r ) &&
               // Before anything that allocates: the depth image is the first.
               CreateAllocator( r ) &&
               CreateSwapchain( r ) &&
               // Before the render pass, which needs the chosen depth format.
               CreateDepthResources( r ) &&
               CreateRenderPass( r ) &&
               CreateFramebuffers( r ) &&
               CreatePerImageSemaphores( r ) &&
               CreateCommandsAndSync( r ) &&
               // Before the pipeline, whose layout embeds this set layout.
               CreateTextureSetLayout( r ) &&
               CreateDescriptorPool( r ) &&
               CreateStaticMeshPipeline( r ) &&
               // Needs the command pool and descriptor pool above.
               CreateWhiteTexture( r ) &&
               // Needs the white texture, which its descriptor set binds.
               CreateGrid( r, kGridDefaultSpacing ) &&
               CreateBorder( r );
    }

    void RendererSetSize( Renderer * r, i32 width, i32 height ) {
        r->fallbackWidth = width;
        r->fallbackHeight = height;
        r->framebufferResized = true;
    }

    void RendererSetViewProjection( Renderer * r, const Mat4 & viewProjection ) {
        RenderView view = {};
        view.width = 1.0f;
        view.height = 1.0f;
        view.viewProjection = viewProjection;
        RendererSetViews( r, &view, 1 );
    }

    RenderMaterial RenderMaterialDefault() {
        RenderMaterial material = {};
        material.albedo = Vec3{ 1.0f, 1.0f, 1.0f };
        material.texture = {};
        return material;
    }

    void RendererSetGridVisible( Renderer * r, bool visible ) {
        r->gridVisible = visible;
    }

    static void DestroyEditOverlayBuffers( Renderer * r ) {
        if( r->editOverlay.lineBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, r->editOverlay.lineBuffer, r->editOverlay.lineAllocation );
        }
        if( r->editOverlay.pointBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, r->editOverlay.pointBuffer, r->editOverlay.pointAllocation );
        }
        r->editOverlay = {};
    }

    // Both halves go through the same upload, so this is the whole difference
    // between them.
    static bool CreateEditOverlayBuffer( Renderer * r, const StaticMeshVertex * vertices, i32 vertexCount,
                                         VkBuffer * outBuffer, VmaAllocation * outAllocation ) {
        const u64 byteCount = (u64)vertexCount * sizeof( StaticMeshVertex );
        bool ok = CreateBuffer( r, byteCount,
                                VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT, 0,
                                outBuffer, outAllocation, nullptr );
        return ok && UploadBuffer( r, *outBuffer, vertices, byteCount );
    }

    bool RendererSetEditOverlay( Renderer * r, const StaticMeshVertex * lineVertices, i32 lineVertexCount,
                                 const StaticMeshVertex * pointVertices, i32 pointVertexCount,
                                 const Mat4 & transform ) {
        // The buffers being replaced may still be referenced by a frame the GPU
        // has not finished with.
        vkDeviceWaitIdle( r->device );
        if( r->borderVertexBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, r->borderVertexBuffer, r->borderVertexAllocation );
            r->borderVertexBuffer = VK_NULL_HANDLE;
            r->borderVertexAllocation = VK_NULL_HANDLE;
            r->borderVertexCount = 0;
        }
        DestroyEditOverlayBuffers( r );

        bool ok = true;
        if( lineVertexCount > 0 ) {
            ok = CreateEditOverlayBuffer( r, lineVertices, lineVertexCount,
                                          &r->editOverlay.lineBuffer, &r->editOverlay.lineAllocation );
            if( ok ) {
                r->editOverlay.lineVertexCount = lineVertexCount;
            }
        }

        if( ok && pointVertexCount > 0 ) {
            ok = CreateEditOverlayBuffer( r, pointVertices, pointVertexCount,
                                          &r->editOverlay.pointBuffer, &r->editOverlay.pointAllocation );
            if( ok ) {
                r->editOverlay.pointVertexCount = pointVertexCount;
            }
        }

        if( !ok ) {
            fprintf( stderr, "Failed to build the edit overlay\n" );
            DestroyEditOverlayBuffers( r );
            return false;
        }

        r->editOverlay.transform = transform;
        r->editOverlay.visible = true;
        return true;
    }

    void RendererClearEditOverlay( Renderer * r ) {
        // Nothing up means nothing to idle the device for, which is what makes
        // this safe to call on every selection change.
        if( r->editOverlay.lineBuffer == VK_NULL_HANDLE &&
            r->editOverlay.pointBuffer == VK_NULL_HANDLE ) {
            r->editOverlay.visible = false;
            return;
        }

        vkDeviceWaitIdle( r->device );
        DestroyEditOverlayBuffers( r );
    }

    bool RendererSetGizmoGeometry( Renderer * r, const StaticMeshVertex * vertices, i32 vertexCount ) {
        vkDeviceWaitIdle( r->device );
        if( r->gizmoVertexBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, r->gizmoVertexBuffer, r->gizmoVertexAllocation );
            r->gizmoVertexBuffer = VK_NULL_HANDLE;
            r->gizmoVertexAllocation = VK_NULL_HANDLE;
            r->gizmoVertexCount = 0;
        }

        if( vertexCount <= 0 ) {
            return true;
        }

        if( !CreateEditOverlayBuffer( r, vertices, vertexCount,
                                      &r->gizmoVertexBuffer, &r->gizmoVertexAllocation ) ) {
            fprintf( stderr, "Failed to build the gizmo geometry\n" );
            return false;
        }

        r->gizmoVertexCount = vertexCount;
        return true;
    }

    void RendererSetGizmoDraw( Renderer * r, const Mat4 & transform, const RenderGizmoRange * ranges,
                               i32 rangeCount ) {
        if( rangeCount > kMaxGizmoRanges ) {
            rangeCount = kMaxGizmoRanges;
        }
        for( i32 i = 0; i < rangeCount; i++ ) {
            r->gizmoRanges[i] = ranges[i];
        }
        r->gizmoRangeCount = rangeCount;
        r->gizmoTransform = transform;
    }

    void RendererSetGizmoVisible( Renderer * r, bool visible ) {
        r->gizmoVisible = visible;
    }

    bool RendererSetGridSpacing( Renderer * r, f32 spacing ) {
        if( spacing <= 0.0f || spacing == r->gridSpacing ) {
            return true;
        }

        // The buffer being replaced may still be referenced by a frame the GPU
        // has not finished with.
        vkDeviceWaitIdle( r->device );
        if( r->gridVertexBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, r->gridVertexBuffer, r->gridVertexAllocation );
            r->gridVertexBuffer = VK_NULL_HANDLE;
            r->gridVertexAllocation = VK_NULL_HANDLE;
            r->gridVertexCount = 0;
        }

        return CreateGrid( r, spacing );
    }

    void RendererSetBorder( Renderer * r, bool visible, Vec3 color ) {
        r->borderVisible = visible;
        r->borderColor = color;
    }

    void RendererSetGridTransform( Renderer * r, const Mat4 & transform ) {
        r->gridTransform = transform;
    }

    void RendererSetViews( Renderer * r, const RenderView * views, i32 count ) {
        if( count > kMaxRenderViews ) {
            count = kMaxRenderViews;
        }
        for( i32 i = 0; i < count; i++ ) {
            r->views[i] = views[i];
        }
        r->viewCount = count;
    }

    void RendererDrawFrame( Renderer * r ) {
        if( r->device == VK_NULL_HANDLE ) {
            return;
        }
        // A recreate deferred by a zero-sized surface is retried here.
        if( r->swapchain == VK_NULL_HANDLE || r->framebufferResized ) {
            r->framebufferResized = false;
            if( !RecreateSwapchain( r ) || r->swapchain == VK_NULL_HANDLE ) {
                return;
            }
        }

        VkFence fence = r->frameInFlight[r->currentFrame];
        vkWaitForFences( r->device, 1, &fence, VK_TRUE, UINT64_MAX );

        u32 imageIndex = 0;
        VkResult acquired = vkAcquireNextImageKHR( r->device, r->swapchain, UINT64_MAX,
                                                   r->imageAvailable[r->currentFrame],
                                                   VK_NULL_HANDLE, &imageIndex );
        if( acquired == VK_ERROR_OUT_OF_DATE_KHR ) {
            RecreateSwapchain( r );
            return;
        }
        if( acquired != VK_SUCCESS && acquired != VK_SUBOPTIMAL_KHR ) {
            fprintf( stderr, "vkAcquireNextImageKHR failed (%d)\n", (int)acquired );
            return;
        }

        // This image may still be in flight from an earlier frame.
        if( r->imagesInFlight[imageIndex] != VK_NULL_HANDLE ) {
            vkWaitForFences( r->device, 1, &r->imagesInFlight[imageIndex], VK_TRUE, UINT64_MAX );
        }
        r->imagesInFlight[imageIndex] = fence;

        vkResetFences( r->device, 1, &fence );

        VkCommandBuffer cmd = r->commandBuffers[r->currentFrame];
        vkResetCommandBuffer( cmd, 0 );
        if( !RecordCommandBuffer( r, cmd, (i32)imageIndex ) ) {
            return;
        }

        VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
        VkSubmitInfo submitInfo = {};
        submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
        submitInfo.waitSemaphoreCount = 1;
        submitInfo.pWaitSemaphores = &r->imageAvailable[r->currentFrame];
        submitInfo.pWaitDstStageMask = &waitStage;
        submitInfo.commandBufferCount = 1;
        submitInfo.pCommandBuffers = &cmd;
        submitInfo.signalSemaphoreCount = 1;
        submitInfo.pSignalSemaphores = &r->renderFinished[imageIndex];

        if( vkQueueSubmit( r->graphicsQueue, 1, &submitInfo, fence ) != VK_SUCCESS ) {
            fprintf( stderr, "vkQueueSubmit failed\n" );
            return;
        }

        VkPresentInfoKHR presentInfo = {};
        presentInfo.sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR;
        presentInfo.waitSemaphoreCount = 1;
        presentInfo.pWaitSemaphores = &r->renderFinished[imageIndex];
        presentInfo.swapchainCount = 1;
        presentInfo.pSwapchains = &r->swapchain;
        presentInfo.pImageIndices = &imageIndex;

        VkResult presented = vkQueuePresentKHR( r->presentQueue, &presentInfo );
        r->currentFrame = ( r->currentFrame + 1 ) % kFramesInFlight;

        if( presented == VK_ERROR_OUT_OF_DATE_KHR || presented == VK_SUBOPTIMAL_KHR ||
            r->framebufferResized ) {
            r->framebufferResized = false;
            RecreateSwapchain( r );
        } else if( presented != VK_SUCCESS ) {
            fprintf( stderr, "vkQueuePresentKHR failed (%d)\n", (int)presented );
        }
    }

    static void DestroyInstanceObjects( Renderer * r ) {
        if( r->surface != VK_NULL_HANDLE && r->ownsSurface ) {
            vkDestroySurfaceKHR( r->instance, r->surface, nullptr );
        }
        r->surface = VK_NULL_HANDLE;
        if( r->debugMessenger != VK_NULL_HANDLE ) {
            auto destroy = (PFN_vkDestroyDebugUtilsMessengerEXT)vkGetInstanceProcAddr(
                r->instance, "vkDestroyDebugUtilsMessengerEXT" );
            if( destroy != nullptr ) {
                destroy( r->instance, r->debugMessenger, nullptr );
            }
        }
        vkDestroyInstance( r->instance, nullptr );
        r->instance = VK_NULL_HANDLE;
    }

    void RendererShutdownDevice( Renderer * r ) {
        // Startup can fail part-way, so everything here is guarded: this has to
        // tear down whatever actually got created.
        if( r->device == VK_NULL_HANDLE ) {
            return;
        }
        vkDeviceWaitIdle( r->device );

        for( i32 i = 0; i < kFramesInFlight; i++ ) {
            if( r->imageAvailable[i] != VK_NULL_HANDLE ) {
                vkDestroySemaphore( r->device, r->imageAvailable[i], nullptr );
            }
            if( r->frameInFlight[i] != VK_NULL_HANDLE ) {
                vkDestroyFence( r->device, r->frameInFlight[i], nullptr );
            }
        }

        DestroySwapchain( r );

        for( i32 i = 0; i < PoolSlotCount( r->staticMeshes ); i++ ) {
            RenderStaticMesh * mesh = PoolAt( r->staticMeshes, i );
            if( mesh != nullptr ) {
                RenderStaticMeshDestroy( r, mesh );
            }
        }
        PoolFree( r->staticMeshes );

        // Before the descriptor pool: destroying that implicitly frees every
        // set allocated from it, but the image, view and sampler each texture
        // points at are its own and still need an explicit teardown. The white
        // fallback lives in here too, so it needs no separate pass.
        for( i32 i = 0; i < PoolSlotCount( r->textures ); i++ ) {
            RenderTexture * texture = PoolAt( r->textures, i );
            if( texture != nullptr ) {
                RenderTextureDestroy( r, texture );
            }
        }
        PoolFree( r->textures );
        r->whiteTexture = {};

        if( r->gridVertexBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, r->gridVertexBuffer, r->gridVertexAllocation );
            r->gridVertexBuffer = VK_NULL_HANDLE;
            r->gridVertexAllocation = VK_NULL_HANDLE;
            r->gridVertexCount = 0;
        }
        DestroyEditOverlayBuffers( r );
        if( r->gizmoVertexBuffer != VK_NULL_HANDLE ) {
            vmaDestroyBuffer( r->allocator, r->gizmoVertexBuffer, r->gizmoVertexAllocation );
            r->gizmoVertexBuffer = VK_NULL_HANDLE;
            r->gizmoVertexAllocation = VK_NULL_HANDLE;
            r->gizmoVertexCount = 0;
        }
        if( r->editPointPipeline != VK_NULL_HANDLE ) {
            vkDestroyPipeline( r->device, r->editPointPipeline, nullptr );
            r->editPointPipeline = VK_NULL_HANDLE;
        }
        if( r->editLinePipeline != VK_NULL_HANDLE ) {
            vkDestroyPipeline( r->device, r->editLinePipeline, nullptr );
            r->editLinePipeline = VK_NULL_HANDLE;
        }
        if( r->gridPipeline != VK_NULL_HANDLE ) {
            vkDestroyPipeline( r->device, r->gridPipeline, nullptr );
            r->gridPipeline = VK_NULL_HANDLE;
        }
        if( r->staticMeshPipeline != VK_NULL_HANDLE ) {
            vkDestroyPipeline( r->device, r->staticMeshPipeline, nullptr );
            r->staticMeshPipeline = VK_NULL_HANDLE;
        }
        if( r->staticMeshPipelineLayout != VK_NULL_HANDLE ) {
            vkDestroyPipelineLayout( r->device, r->staticMeshPipelineLayout, nullptr );
            r->staticMeshPipelineLayout = VK_NULL_HANDLE;
        }
        if( r->descriptorPool != VK_NULL_HANDLE ) {
            vkDestroyDescriptorPool( r->device, r->descriptorPool, nullptr );
            r->descriptorPool = VK_NULL_HANDLE;
        }
        if( r->textureSetLayout != VK_NULL_HANDLE ) {
            vkDestroyDescriptorSetLayout( r->device, r->textureSetLayout, nullptr );
            r->textureSetLayout = VK_NULL_HANDLE;
        }

        if( r->commandPool != VK_NULL_HANDLE ) {
            vkDestroyCommandPool( r->device, r->commandPool, nullptr );
        }
        if( r->renderPass != VK_NULL_HANDLE ) {
            vkDestroyRenderPass( r->device, r->renderPass, nullptr );
        }

        // After every buffer and image above has gone back: VMA asserts if it
        // is torn down with allocations still outstanding.
        if( r->allocator != VK_NULL_HANDLE ) {
            vmaDestroyAllocator( r->allocator );
            r->allocator = VK_NULL_HANDLE;
        }

        vkDestroyDevice( r->device, nullptr );
        r->device = VK_NULL_HANDLE;
    }

    void RendererShutdown( Renderer * r ) {
        RendererShutdownDevice( r );
        if( r->instance != VK_NULL_HANDLE ) {
            DestroyInstanceObjects( r );
        }
    }

} // namespace sol
